apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

commonLabels:
  app.kubernetes.io/environment: production

images:
- name: quay.io/redhattraining/exoplanets
  newTag: v1.0

patches:
- path: resource-limits.yaml
