apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: dev-
images:
- name: quay.io/redhattraining/exoplanets
  newTag: v1.0
replicas:
- name: user-service
  count: 1
