apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_USER: "exoplanets"
  DB_PASSWORD: "apppassword"
  DB_NAME: "exoplanets"
  DB_SSLMODE: "disable"
  LOG_LEVEL: "INFO"
