apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  labels:
    app: database-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
      - name: database-service
        image: quay.io/sclorg/postgresql-15-c9s
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: exoplanets
        - name: POSTGRESQL_PASSWORD
          value: apppassword
        - name: POSTGRESQL_DATABASE
          value: exoplanets
